### ISSUE TITLE
Call to undefined function ctype_digit()

### ISSUE THREAD

**Issue by davidbnk** [phpmyadmin/docker#115]
I'm getting the following error  in `/var/log/nginx-error.log` while using phpmyadmin docker image with jwilder nginx-proxy. I have used both in conjunction in the past and I can't identify whats causing the problem right now

```
2017/04/06 15:41:37 [error] 25#25: *138 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ExpressionLanguage\ctype_digit() in /www/vendor/symfony/expression-language/Lexer.php:48
Stack trace:
#0 /www/vendor/symfony/expression-language/ExpressionLanguage.php(108): Symfony\Component\ExpressionLanguage\Lexer->tokenize('n > 1')
#1 /www/vendor/symfony/expression-language/ExpressionLanguage.php(81): Symfony\Component\ExpressionLanguage\ExpressionLanguage->parse('n > 1', Array)
#2 /www/vendor/phpmyadmin/motranslator/src/Translator.php(257): Symfony\Component\ExpressionLanguage\ExpressionLanguage->evaluate('n > 1', Array)
#3 /www/vendor/phpmyadmin/motranslator/src/Translator.php(285): PhpMyAdmin\MoTranslator\Translator->selectString(25)
#4 /www/vendor/phpmyadmin/motranslator/src/functions.php(108): PhpMyAdmin\MoTranslator\Translator->ngettext('%s table', '%s tables', 25)
#5 /www/templates/database/structure/body_for_table_summary.phtml(6): _ngettext('%s table', '%s tables', 25)
#6 /www/libraries/Template.php(15" while reading response header from upstream, client: 172.19.0.2, server: _, request: "GET /db_structure.php?db=mydb HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "my.host.com"
```

**Comment by davidbnk** [comment]
Image details: 

```
[
    {
        "Id": "sha256:a440c461fdf4444baa0c1adf321bd95478ab85d8f8747409e536ac202ab7d1b9",
        "RepoTags": [
            "phpmyadmin/phpmyadmin:latest"
        ],
        "RepoDigests": [
            "phpmyadmin/phpmyadmin@sha256:2f72aa4236a0bb5fb77d9b976254799b3cd38dc744c9bf0985902f7586c89a1c"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-04-05T19:37:47.09578495Z",
        "Container": "c808112849a6a76c4284b940fc1797713f32e695feec3c3e7b414e9580e3226b",
        "ContainerConfig": {
            "Hostname": "84baa8e89c00",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "VERSION=4.7.0",
                "URL=https://files.phpmyadmin.net/phpMyAdmin/4.7.0/phpMyAdmin-4.7.0-all-languages.tar.gz"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"phpmyadmin\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:7c4f7ccbc72ba50b95c2d656081bc8cc33e7d7785b0346cf85e65cb6ea24d472",
            "Volumes": {
                "/sessions": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/run.sh"
            ],
            "OnBuild": [],
            "Labels": {
                "version": "4.7.0"
            }
        },
        "DockerVersion": "1.12.6-cs6",
        "Author": "",
        "Config": {
            "Hostname": "84baa8e89c00",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "VERSION=4.7.0",
                "URL=https://files.phpmyadmin.net/phpMyAdmin/4.7.0/phpMyAdmin-4.7.0-all-languages.tar.gz"
            ],
            "Cmd": [
                "phpmyadmin"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:7c4f7ccbc72ba50b95c2d656081bc8cc33e7d7785b0346cf85e65cb6ea24d472",
            "Volumes": {
                "/sessions": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/run.sh"
            ],
            "OnBuild": [],
            "Labels": {
                "version": "4.7.0"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 118027208,
        "VirtualSize": 118027208,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:23b9c7b43573dd164619ad59e9d51eda4095926729f59d5f22803bcbe9ab24c2",
                "sha256:b07cd6ce70bba4c05a716e1c1ee4f83d9c544db71855ca32904607dc97a0729c",
                "sha256:02f16dbcb79fa723ef01620dd65624196dd3f59e80bd38b2767503223cb807a7",
                "sha256:0c98ed3412a1e9017f2ca4cf23d60c4e38bfbf98562538b01a63b8c9ef5c7532",
                "sha256:9f539a88cdaf4680cbf9945ce267d2aa2af60776c6357af0e6459c0216f3b1f5",
                "sha256:32ea225f924169ee06e24f4ecf247b3da83171252af26b19d73f4e3e7c688467"
            ]
        }
    }
]
```

**Comment by davidbnk** [comment]
I can confirm the problem is happening only on 4.7.0-1 
I reverted back to 4.6.6-2 and the error is not occurring

**Comment by nijel** [comment]
Thanks for pointing this out, there is undocumented dependency on ctype in Symfony ExpressionLanguage, I've submitted PR to fix that there: https://github.com/symfony/symfony/pull/22325

**Comment by nijel** [comment]
Reopening to remove the dependency on 4.7.1 release.

**Comment by emanuelb** [comment]
The dependency can be removed now as 4.7.1 is already set in Dockerfile

**Comment by nijel** [comment]
Thanks for poiting out!
