### ISSUE TITLE
Ssql connection errors

### ISSUE THREAD

**Issue by kenpachizero** [phpmyadmin/docker#391]
Hi All,
I have two issue, a request and a problem

Request:
I have put in the config.user.inc.php two server configs, if one them is not running all of phpmyadmin wont load with this error:
`Fatal error: Uncaught ErrorException: mysqli::real_connect(): (HY000/2002): No route to host in /var/www/html/libraries/classes/Dbal/DbiMysqli.php:122 Stack trace: #0 [internal function]: PhpMyAdmin\ErrorHandler->handleError(2, 'mysqli::real_co...', '/var/www/html/l...', 122) #1 /var/www/html/libraries/classes/Dbal/DbiMysqli.php(122): mysqli->real_connect('172.31.255.235', 'root', 'password...', '', 0, '', 0) #2 /var/www/html/libraries/classes/DatabaseInterface.php(1877): PhpMyAdmin\Dbal\DbiMysqli->connect('root', 'password...', Array) #3 /var/www/html/libraries/classes/Common.php(604): PhpMyAdmin\DatabaseInterface->connect(256) #4 /var/www/html/libraries/classes/Common.php(233): PhpMyAdmin\Common::connectToDatabaseServer(Object(PhpMyAdmin\DatabaseInterface), Object(PhpMyAdmin\Plugins\Auth\AuthenticationConfig)) #5 /var/www/html/index.php(40): PhpMyAdmin\Common::run() #6 {main} thrown in /var/www/html/libraries/classes/Dbal/DbiMysqli.php on line 122`

Would there be a way to make it load if others are working but just says cant connect to that specific one?

Problem:
I have two mariadb setup in the config.user.inc.php with username and password, when i connect in into phpmyadmin i get the following error:
![Screenshot 2022-12-15 094847](https://user-images.githubusercontent.com/34297518/207739772-3f2d8ddb-336c-4eb6-8ac5-ee74825ddec5.png)

but all i did was load the page i have not clicked on anything yet.

**Comment by williamdes** [comment]
Hi,

As the error says, there is probably "No route to host" from a networking point of view.
Are you using docker?

Also could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)
And let me know if it is fixed?

**Comment by kenpachizero** [comment]
Hi William, 
Yes i am using docker and i get the same error
![image](https://user-images.githubusercontent.com/34297518/207761139-ee2b7891-e305-42d4-9d09-430a2c3643f4.png)

**Comment by williamdes** [comment]
Thanks for confirming, can you send your docker compose file?
And configuration file please?

**Comment by kenpachizero** [comment]
Hi William,
Here is my config file:
```
<?php
$cfg['environment'] = 'development';
$i++;
$cfg['Servers'][$i]['host'] = '172.31.255.235'; 
$cfg['Servers'][$i]['user'] = 'root'; 
$cfg['Servers'][$i]['password'] = 'password'; 
$cfg['Servers'][$i]['auth_type'] = 'config';
$i++;
$cfg['Servers'][$i]['host'] = '172.31.255.252'; 
$cfg['Servers'][$i]['user'] = 'root'; 
$cfg['Servers'][$i]['password'] = 'password'; 
$cfg['Servers'][$i]['auth_type'] = 'config';
```
and here is the portainer screen:
![image](https://user-images.githubusercontent.com/34297518/207766542-9241c211-3975-4b51-a6f1-55c03e8f179e.png)

**Comment by williamdes** [comment]
Okay, there is nothing wrong except `$cfg['environment'] = 'development'; ` unless you do some phpMyAdmin bug fixing or development of phpMyAdmin.

But that's not the bug I think, can you check in your browser developer console what request fails? (it will be a 200 OK)I would bet on some `/config/get`

**Comment by kenpachizero** [comment]
Hi,

I changed from development to production and same issue.
Here is the pic from he console window and from the network windows
![image](https://user-images.githubusercontent.com/34297518/207772214-d9452032-8bc1-45fc-9726-0ceddb9f0ad1.png)
![image](https://user-images.githubusercontent.com/34297518/207772264-838a8ac8-8a92-48ef-abe0-0a6f9a2ed6dc.png)

**Comment by kenpachizero** [comment]
oh and the "$cfg['environment'] = 'development';" was in that files by default so i left it there and just added my stuff to the end

**Comment by williamdes** [comment]
> oh and the "$cfg['environment'] = 'development';" was in that files by default so i left it there and just added my stuff to the end

By portainer?

Can you click onto the two last requests "/config/set" , I am pretty sure this are the requests that make the error

**Comment by kenpachizero** [comment]
i think i actually added that when i was trying to get it working so was probably left over from that attempt, also here is the last two /config/set requests:
![image](https://user-images.githubusercontent.com/34297518/207792798-8cf8e917-d6f6-49dc-88e6-60dcf9ff45c4.png)
![image](https://user-images.githubusercontent.com/34297518/207792870-6edc3b40-39aa-4410-9aef-50e73c6125ed.png)
and i could save it all as a har file but i cant upload that so i renamed it to a txt file.
[192.168.0.43_Archive [22-12-15 16-52-01].txt](https://github.com/phpmyadmin/docker/files/10234469/192.168.0.43_Archive.22-12-15.16-52-01.txt)

**Comment by williamdes** [comment]
Thanks, I forgot to day the "Response" tab is the most interesting
You can paste the json contents directly here as text

**Comment by kenpachizero** [comment]
1:
{"reload_flag":"1","success":false,"error":""}
2:
{"reload_flag":"1","success":false,"error":""}

**Comment by williamdes** [comment]
> 1: {"reload_flag":"1","success":false,"error":""} 2: {"reload_flag":"1","success":false,"error":""}

Thanks, I will check the code and see how I can provide other debug instructions

What do say config/get requests responses?

**Comment by williamdes** [comment]
Thanks, this will help a lot
Seems like there is some issue with the configuration storage
